default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "gkfsdzh-bd75862"

      # User/password auth
      user: " "
      password: " "

      role: "ACCOUNTADMIN"
      database: "analytics"
      warehouse: "dbt_transforming"
      schema: "datamart"
      threads: 1
      client_session_keep_alive: False
      query_tag: "anything"

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)